# Generated by Django 4.1.7 on 2023-03-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
